service: arc-voting-system

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1
  stage: v1
  environment:
    VOTES_TABLE: ${self:service}-votes-${self:provider.stage}
    CONNECTIONS_TABLE: ${self:service}-connections-${self:provider.stage}
    AWS_WEBSOCKET_API_DOMAIN_NAME:
      Ref: WebsocketsApi
    AWS_WEBSOCKET_API_STAGE: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.VOTES_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CONNECTIONS_TABLE}"
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource:
            - "arn:aws:execute-api:${self:provider.region}:*:*/@connections/*"

package:
  patterns:
    - src/vote-client.min.js

functions:
  connect:
    handler: src/handlers/connect.handler
    events:
      - websocket:
          route: $connect
          cors: true

  disconnect:
    handler: src/handlers/disconnect.handler
    events:
      - websocket:
          route: $disconnect
          cors: true

  vote:
    handler: src/handlers/vote.handler
    events:
      - websocket:
          route: $default
          cors: true

  serveClient:
    handler: src/handlers/serve-client.handler
    events:
      - http:
          path: /client/vote-client.min.js
          method: get
          cors: true

resources:
  Resources:
    VotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.VOTES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: voteId
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
          - AttributeName: voteId
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CONNECTIONS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

outputs:
  WebSocketURL:
    Description: "WebSocket API URL"
    Value: !Sub "wss://${WebsocketsApi}.execute-api.${AWS::Region}.amazonaws.com/${self:provider.stage}"
